snowflake-url: "https://nl76762.us-central1.gcp.snowflakecomputing.com:443"
snowflake-user: "scalabrese"
snowflake-password: "PodeT8w5"
snowflake-warehouse: "WH_SCALABRESE"
snowflake-db: 'DB_SCALABRESE'
snowflake-schema: "DEMO"

pipelines:
  demo:
    tables:
      restaurant: "RESTAURANT"
      rating_raw: "RATING_RAW"
      rating: "RATING"
      order_raw: "ORDER_RAW"
      order: "ORDER"
      payment: "PAYMENT"
    streams:
      rating_raw: "RATING_RAW_STREAM"
      order_raw: "ORDER_RAW_STREAM"
      payment: "PAYMENT_STREAM"
    stages:
      restaurant: "RESTAURANT_STAGE"
      restaurant_local_path: "ingest/restaurant"
      payment: "PAYMENT_STAGE"
      payment_local_path: "ingest/payment"


servlets:
  generator:
    baseUrl: "http://localhost"
    basepath: "/generator"
    port: 8100
    endpoints:
      generate-orders: "/getOrders"
      generate-payments: "/getPayments"
      generate-ratings: "/getRatings"
      generate-restaurants: "/getRestaurants"