#snowflake-url: "https://inspire.east-us-2.azure.snowflakecomputing.com:443"
snowflake-url: "https://LL76183.east-us-2.azure.snowflakecomputing.com:443"
#snowflake-user: "RA_OBJOWNR_DEV"
snowflake-user: "demo"
#snowflake-password: "=5*7wVnf)z#$c(G8"
snowflake-password: "Simon123!"
#snowflake-warehouse: "RA_UA_WH"
snowflake-warehouse: "COMPUTE_WH"
#snowflake-db: 'RDS_DEV'
snowflake-db: 'DEMO'
#snowflake-schema: "BWW"
snowflake-schema: "TT_DPS"

pipeline:
  tables:
    industry-code: "INDUSTRY_CODE"
    employee-code: "EMPLOYEE_CODE"
    industry-code-l-or-d: "INDUSTRY_CODE_L_OR_D"
    industry-code-stream: "INDUSTRY_CODE_STREAM"
    industry-code-first2: "INDUSTRY_CODE_FIRST2"
    industry-employee: "EMPLOYEE_INDUSTRY"