snowflake-url: "https://nl76762.us-central1.gcp.snowflakecomputing.com:443"
snowflake-user: "scalabrese"
snowflake-password: "PodeT8w5"
snowflake-warehouse: "WH_SCALABRESE"
snowflake-db: 'DB_SCALABRESE'
snowflake-schema: "DEMO"

pipelines:
  demo:
    tables:
      restaurant: "DIM_RESTAURANT"
      rating_raw: "RATING_RAW"
      rating: "TRAN_RATING"
      order_raw: "ORDER_RAW"
      order: "TRAN_ORDER"
      payment: "TRAN_PAYMENT"
      dq_payment_more_than_order: "DQ_PAYMENT_MT_ORDER"
      amex_rating_gt_50: "ORDER_AMEX_RATING_GT_50"
      best_rating_restaurant_30days: "BEST_RATING_RESTAURANT_30DD"
    streams:
      rating_raw: "RATING_RAW_STREAM"
      order_raw: "ORDER_RAW_STREAM"
      payment_stage: "PAYMENT_STAGE_STREAM"
      payment: "TRAN_PAYMENT_STREAM"
      order: "TRAN_ORDER_STREAM"
    stages:
      restaurant: "RESTAURANT_STAGE"
      restaurant_local_path: "ingest/restaurant"
      payment: "PAYMENT_STAGE"
      payment_local_path: "ingest/payment"


servlets:
  generator:
    baseUrl: "http://localhost"
    basepath: "/generator"
    port: 8100
    endpoints:
      generate-orders: "/getOrders"
      generate-payments: "/getPayments"
      generate-ratings: "/getRatings"
      generate-restaurants: "/getRestaurants"