snowflake-url: "https://nl76762.us-central1.gcp.snowflakecomputing.com:443"
#snowflake-url: "https://LL76183.east-us-2.azure.snowflakecomputing.com:443"
#snowflake-user: "RA_OBJOWNR_DEV"
snowflake-user: "scalabrese"
#snowflake-password: "=5*7wVnf)z#$c(G8"
snowflake-password: "PodeT8w5"
#snowflake-warehouse: "WH_SCALABRESE"
snowflake-warehouse: "WH_SCALABRESE"
#snowflake-db: 'RDS_DEV'
snowflake-db: 'DB_SCALABRESE'
#snowflake-schema: "BWW"
snowflake-schema: "DEMO"

pipeline:
  tables:
    industry-code: "INDUSTRY_CODE"
    employee-code: "EMPLOYEE_CODE"
    industry-code-l-or-d: "INDUSTRY_CODE_L_OR_D"
    industry-code-stream: "INDUSTRY_CODE_STREAM"
    industry-code-first2: "INDUSTRY_CODE_FIRST2"
    industry-employee: "EMPLOYEE_INDUSTRY"

servlets:
  generator:
    baseUrl: "http://localhost"
    basepath: "/generator"
    port: 8100
    endpoints:
      generate-industries: "/getIndustries"
      generate-employees: "/getEmployees"