snowflake-url: "https://nl76762.us-central1.gcp.snowflakecomputing.com:443"
snowflake-user: "scalabrese"
snowflake-password: "PodeT8w5"
snowflake-warehouse: "WH_SCALABRESE"
snowflake-db: 'DB_SCALABRESE'
snowflake-schema: "DEMO"

pipeline:
  tables:
    industry-code: "INDUSTRY_CODE"
    employee-code: "EMPLOYEE_CODE"
    industry-code-l-or-d: "INDUSTRY_CODE_L_OR_D"
    industry-code-stream: "INDUSTRY_CODE_STREAM"
    industry-code-first2: "INDUSTRY_CODE_FIRST2"
    industry-employee: "EMPLOYEE_INDUSTRY"

servlets:
  generator:
    baseUrl: "http://localhost"
    basepath: "/generator"
    port: 8100
    endpoints:
      generate-industries: "/getIndustries"
      generate-employees: "/getEmployees"